-- 陈哥厨房数据库单一基线
-- 适用范围：全新 PostgreSQL 15+ 数据库，不兼容旧 V1/V2/V3 数据。

-- 用户：微信身份与管理端账号共用一个账号体系。
CREATE TABLE sys_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openid      VARCHAR(64),
    username    VARCHAR(32),
    password    VARCHAR(100),
    nickname    VARCHAR(50) NOT NULL,
    avatar_url  VARCHAR(500),
    role        VARCHAR(10) NOT NULL DEFAULT 'user',
    status      VARCHAR(10) NOT NULL DEFAULT 'active',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by   VARCHAR(64),
    update_by   VARCHAR(64),
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_sys_user_identity CHECK (openid IS NOT NULL OR username IS NOT NULL),
    CONSTRAINT ck_sys_user_role CHECK (role IN ('user', 'admin')),
    CONSTRAINT ck_sys_user_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT ck_sys_user_password CHECK (password IS NULL OR char_length(password) >= 50)
);

CREATE UNIQUE INDEX uk_sys_user_openid
    ON sys_user(openid) WHERE openid IS NOT NULL AND deleted = FALSE;
CREATE UNIQUE INDEX uk_sys_user_username
    ON sys_user(username) WHERE username IS NOT NULL AND deleted = FALSE;
CREATE INDEX idx_sys_user_role_status
    ON sys_user(role, status) WHERE deleted = FALSE;

-- 文件元数据：对象存储中只保存对象，数据库保存稳定对象键。
CREATE TABLE sys_file (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name    VARCHAR(255) NOT NULL,
    file_key         VARCHAR(500) NOT NULL,
    bucket           VARCHAR(100) NOT NULL,
    size_bytes       BIGINT NOT NULL,
    mime_type        VARCHAR(100) NOT NULL,
    thumb_key        VARCHAR(500),
    thumb_size_bytes BIGINT,
    thumb_mime_type  VARCHAR(100),
    upload_by        BIGINT NOT NULL,
    create_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by        VARCHAR(64),
    update_by        VARCHAR(64),
    deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_sys_file_upload_by FOREIGN KEY (upload_by) REFERENCES sys_user(id),
    CONSTRAINT ck_sys_file_size CHECK (size_bytes >= 0),
    CONSTRAINT ck_sys_file_thumb_size CHECK (thumb_size_bytes IS NULL OR thumb_size_bytes >= 0)
);

CREATE UNIQUE INDEX uk_sys_file_object
    ON sys_file(bucket, file_key) WHERE deleted = FALSE;
CREATE INDEX idx_sys_file_upload_by
    ON sys_file(upload_by) WHERE deleted = FALSE;

-- 菜品分类。
CREATE TABLE dish_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(20) NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    status      VARCHAR(10) NOT NULL DEFAULT 'active',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by   VARCHAR(64),
    update_by   VARCHAR(64),
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_dish_category_status CHECK (status IN ('active', 'hidden'))
);

CREATE UNIQUE INDEX uk_dish_category_name
    ON dish_category(name) WHERE deleted = FALSE;
CREATE INDEX idx_dish_category_sort
    ON dish_category(sort_order, id) WHERE deleted = FALSE;

-- 菜品；图片仅关联 sys_file，不持久化有有效期的预签名 URL。
CREATE TABLE dish_info (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50) NOT NULL,
    description   VARCHAR(500),
    image_file_id BIGINT NOT NULL,
    category_id   BIGINT NOT NULL,
    cooking_time  INTEGER,
    status        VARCHAR(15) NOT NULL DEFAULT 'normal',
    is_listed     BOOLEAN NOT NULL DEFAULT TRUE,
    create_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by     VARCHAR(64),
    update_by     VARCHAR(64),
    deleted       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_dish_info_file FOREIGN KEY (image_file_id) REFERENCES sys_file(id),
    CONSTRAINT fk_dish_info_category FOREIGN KEY (category_id) REFERENCES dish_category(id),
    CONSTRAINT ck_dish_info_cooking_time CHECK (cooking_time IS NULL OR cooking_time > 0),
    CONSTRAINT ck_dish_info_status CHECK (status IN ('normal', 'out_of_stock', 'unavailable'))
);

CREATE INDEX idx_dish_info_category
    ON dish_info(category_id) WHERE deleted = FALSE;
CREATE UNIQUE INDEX uk_dish_info_name
    ON dish_info(name) WHERE deleted = FALSE;
CREATE INDEX idx_dish_info_user_list
    ON dish_info(category_id, status, is_listed) WHERE deleted = FALSE;
CREATE INDEX idx_dish_info_image_file
    ON dish_info(image_file_id) WHERE image_file_id IS NOT NULL AND deleted = FALSE;

-- 订单主表。
CREATE TABLE biz_order (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL,
    meal_type        VARCHAR(10) NOT NULL,
    meal_date        DATE NOT NULL,
    status           VARCHAR(15) NOT NULL DEFAULT 'pending',
    taste_tags       JSONB NOT NULL DEFAULT '[]'::JSONB,
    dietary_notes    VARCHAR(500),
    special_requests VARCHAR(500),
    create_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by        VARCHAR(64),
    update_by        VARCHAR(64),
    deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_biz_order_user FOREIGN KEY (user_id) REFERENCES sys_user(id),
    CONSTRAINT ck_biz_order_meal_type CHECK (meal_type IN ('breakfast', 'lunch', 'dinner')),
    CONSTRAINT ck_biz_order_status CHECK (status IN ('pending', 'preparing', 'cooking', 'completed', 'cancelled')),
    CONSTRAINT ck_biz_order_taste_tags CHECK (
        jsonb_typeof(taste_tags) = 'array' AND jsonb_array_length(taste_tags) <= 10
    )
);

CREATE INDEX idx_biz_order_user_date
    ON biz_order(user_id, meal_date DESC, create_time DESC) WHERE deleted = FALSE;
CREATE INDEX idx_biz_order_status_date
    ON biz_order(status, meal_date, create_time) WHERE deleted = FALSE;

-- 订单菜品快照。
CREATE TABLE biz_order_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL,
    dish_id     BIGINT NOT NULL,
    dish_name   VARCHAR(50) NOT NULL,
    quantity    INTEGER NOT NULL DEFAULT 1,
    is_extra    BOOLEAN NOT NULL DEFAULT FALSE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by   VARCHAR(64),
    update_by   VARCHAR(64),
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_biz_order_item_order FOREIGN KEY (order_id) REFERENCES biz_order(id),
    CONSTRAINT fk_biz_order_item_dish FOREIGN KEY (dish_id) REFERENCES dish_info(id),
    CONSTRAINT ck_biz_order_item_quantity CHECK (quantity BETWEEN 1 AND 20),
    CONSTRAINT ck_biz_order_item_dish_name CHECK (btrim(dish_name) <> '')
);

CREATE INDEX idx_biz_order_item_order
    ON biz_order_item(order_id, id) WHERE deleted = FALSE;
CREATE INDEX idx_biz_order_item_dish
    ON biz_order_item(dish_id) WHERE deleted = FALSE;

-- 订单事件日志；事件与订单变更在同一事务中落库。
CREATE TABLE biz_order_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT NOT NULL,
    event_type  VARCHAR(32) NOT NULL,
    actor_id    BIGINT,
    from_status VARCHAR(15),
    to_status   VARCHAR(15),
    item_count  INTEGER,
    description VARCHAR(500) NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by   VARCHAR(64),
    update_by   VARCHAR(64),
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_biz_order_event_order FOREIGN KEY (order_id) REFERENCES biz_order(id),
    CONSTRAINT fk_biz_order_event_actor FOREIGN KEY (actor_id) REFERENCES sys_user(id),
    CONSTRAINT ck_biz_order_event_type CHECK (
        event_type IN ('order_created', 'items_added', 'user_cancelled', 'status_changed')
    ),
    CONSTRAINT ck_biz_order_event_statuses CHECK (
        (from_status IS NULL OR from_status IN ('pending', 'preparing', 'cooking', 'completed', 'cancelled'))
        AND (to_status IS NULL OR to_status IN ('pending', 'preparing', 'cooking', 'completed', 'cancelled'))
    ),
    CONSTRAINT ck_biz_order_event_item_count CHECK (item_count IS NULL OR item_count > 0),
    CONSTRAINT ck_biz_order_event_description CHECK (btrim(description) <> '')
);

CREATE INDEX idx_biz_order_event_order
    ON biz_order_event(order_id, id) WHERE deleted = FALSE;
CREATE INDEX idx_biz_order_event_type
    ON biz_order_event(event_type, create_time DESC) WHERE deleted = FALSE;

-- 站内通知与微信订阅消息共用持久化投递记录。
CREATE TABLE sys_notification (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         BIGINT NOT NULL,
    order_id         BIGINT NOT NULL,
    recipient_id     BIGINT NOT NULL,
    channel          VARCHAR(16) NOT NULL,
    notification_type VARCHAR(32) NOT NULL,
    title            VARCHAR(100) NOT NULL,
    content          VARCHAR(500) NOT NULL,
    delivery_status  VARCHAR(16) NOT NULL,
    attempt_count    INTEGER NOT NULL DEFAULT 0,
    next_attempt_time TIMESTAMP,
    processing_time  TIMESTAMP,
    sent_time        TIMESTAMP,
    read_time        TIMESTAMP,
    last_error       VARCHAR(500),
    create_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by        VARCHAR(64),
    update_by        VARCHAR(64),
    deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_sys_notification_event FOREIGN KEY (event_id) REFERENCES biz_order_event(id),
    CONSTRAINT fk_sys_notification_order FOREIGN KEY (order_id) REFERENCES biz_order(id),
    CONSTRAINT fk_sys_notification_recipient FOREIGN KEY (recipient_id) REFERENCES sys_user(id),
    CONSTRAINT uk_sys_notification_delivery UNIQUE (event_id, recipient_id, channel),
    CONSTRAINT ck_sys_notification_channel CHECK (channel IN ('in_app', 'wechat')),
    CONSTRAINT ck_sys_notification_type CHECK (
        notification_type IN ('new_order', 'items_added', 'order_cancelled')
    ),
    CONSTRAINT ck_sys_notification_status CHECK (
        delivery_status IN ('delivered', 'pending', 'processing', 'sent', 'failed', 'dead')
    ),
    CONSTRAINT ck_sys_notification_attempts CHECK (attempt_count >= 0),
    CONSTRAINT ck_sys_notification_text CHECK (btrim(title) <> '' AND btrim(content) <> '')
);

CREATE INDEX idx_sys_notification_in_app_poll
    ON sys_notification(recipient_id, id DESC)
    WHERE channel = 'in_app' AND deleted = FALSE;
CREATE INDEX idx_sys_notification_unread
    ON sys_notification(recipient_id, id)
    WHERE channel = 'in_app' AND read_time IS NULL AND deleted = FALSE;
CREATE INDEX idx_sys_notification_delivery
    ON sys_notification(delivery_status, next_attempt_time, id)
    WHERE channel = 'wechat' AND deleted = FALSE;

-- 收藏；部分唯一索引允许取消收藏（逻辑删除）后再次收藏。
CREATE TABLE biz_favorite (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    dish_id     BIGINT NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_by   VARCHAR(64),
    update_by   VARCHAR(64),
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_biz_favorite_user FOREIGN KEY (user_id) REFERENCES sys_user(id),
    CONSTRAINT fk_biz_favorite_dish FOREIGN KEY (dish_id) REFERENCES dish_info(id)
);

CREATE UNIQUE INDEX uk_biz_favorite_user_dish
    ON biz_favorite(user_id, dish_id) WHERE deleted = FALSE;
CREATE INDEX idx_biz_favorite_user
    ON biz_favorite(user_id, create_time DESC) WHERE deleted = FALSE;

-- 私有项目的初始账号和基础分类。生产环境通过 Flyway placeholders 注入账号信息。
INSERT INTO sys_user (
    openid, username, password, nickname, role, status, create_by, update_by
) VALUES (
    '${admin_openid}', '${admin_username}', '${admin_password_hash}', '陈哥', 'admin', 'active', 'system', 'system'
), (
    '${user_openid}', NULL, NULL, '淇姐', 'user', 'active', 'system', 'system'
);

INSERT INTO dish_category (name, sort_order, status, create_by, update_by) VALUES
    ('家常菜', 1, 'active', 'system', 'system'),
    ('汤羹', 2, 'active', 'system', 'system'),
    ('主食', 3, 'active', 'system', 'system'),
    ('小吃', 4, 'active', 'system', 'system'),
    ('专属私房菜', 5, 'active', 'system', 'system');
