# 开发环境配置
spring:
  datasource:
    url: jdbc:postgresql://101.34.58.32:5432/kitchen?currentSchema=public&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: f9PJdfAn)xf&

minio:
  endpoint: http://101.34.58.32:12090
  access-key: admin
  secret-key: Her0neverdie!
  bucket: smart-om

logging:
  level:
    com.der.kitchen: debug
